dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - coverage run tests.py --omit bot.py
after_success:
  - codecov