dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - coverage run tests.py
env:
  - CODECOV_TOKEN="5dcc6502-77e9-4fd2-8aa2-cead6146496c"
after_success:
  - codecov